workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
    cache:
      cache_paths:
      - $FCI_BUILD_DIR/build
    triggering:
      events:
      - push
      - pull_request
      branch_patterns:
      - pattern: "*"
        include: true
        source: true
    scripts:
    - flutter packages pub get
    - flutter test --coverage
    - flutter pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart,license.dart,
      home_view.dart,home_router.dart,new_detail.dart,new_detail_router.dart,current_player.dart,detail_podcast_view.dart,detail_podcast_router.dart,all_podcast_view.dart,detail_podcast_router.dart,all_podcast_view.dart,all_podcast_router.dart,
      podcast_controls.dart,settings.dart,settings_router.dart,settings_detail.dart,settings_detail_router.dart,time_table_view.dart,time_table_router.dart,
      bottom_bar.dart,connection_contract.dart,custom_image.dart,neumorfism.dart,notification_subscription_contract.dart,player_view.dart,top_bar.dart$'
    artifacts:
    - coverage/lcov.info