name: cuacfm
description: A radio station with radioco integration.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependency_overrides:
    firebase_core: 0.4.3+1

dependencies:
  flutter:
      sdk: flutter
  flutter_localizations:
    sdk: flutter

  verbal_expressions: "^0.4.0"
  audioplayers: "^0.13.6"
  intl: "^0.16.0"
  xml2json: "^4.1.1"
  cupertino_icons: "^0.1.3"
  device_info: "^0.4.1+5"
  http: "^0.12.0+4"
  html: ^0.14.0
  share: ^0.6.3+5
  shared_preferences: ^0.5.4+9
  injector: ^1.0.5
  animations: ^1.0.0+5
  cached_network_image: ^2.0.0
  flutter_html: ^0.11.1
  url_launcher: ^5.4.1
  font_awesome_flutter: ^8.7.0
  maps_launcher: ^1.2.0
  photo_view: ^0.9.2
  progress_indicators: ^0.1.4
  connectivity: ^0.4.6+2
  uuid: ^2.0.4
  provider: ^4.0.4
  firebase_core: 0.4.3+1
  firebase_messaging: 6.0.9
  firebase_performance: 0.3.1+5
  firebase_crashlytics: 0.1.2+3
  firebase_analytics: 5.0.9
  firebase_in_app_messaging: ^0.1.1+3
  mock_web_server: ^4.1.1
  mockito: ^4.1.1
  countdown: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/graphics/icon_info.png
      - assets/graphics/play_podcast.png
      - assets/graphics/cuac-logo.png
      - assets/graphics/empty-logo.png
      - assets/graphics/categories/tv.jpeg
      - assets/graphics/categories/news.jpeg
      - assets/graphics/categories/sports.jpeg
      - assets/graphics/categories/society.jpeg
      - assets/graphics/categories/education.jpeg
      - assets/graphics/categories/comedy.jpeg
      - assets/graphics/categories/music.jpeg
      - assets/graphics/categories/science.jpeg
      - assets/graphics/categories/arts.jpeg
      - assets/graphics/categories/goverment.jpeg
      - assets/graphics/categories/health.jpeg
      - assets/graphics/categories/tech.jpeg
      - assets/graphics/watch.jpg

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Light.ttf